apiVersion : apps/v1
kind: Deployment
metadata:
  name: "template1-f1f8"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: "template1-f1f8"
  template:
    metadata:
      labels:
        app: "template1-f1f8"
    spec:
      containers:
        - name: "template1-f1f8"
          image: "dasdac.azurecr.io/template1"
          ports:
          - containerPort: 12