apiVersion: v1
kind: Service
metadata:
    name: "template1-9e44"
    labels:
        app: "template1-9e44"
spec:
    type: LoadBalancer
    ports:
    - port: 22
      targetPort: 22
      protocol: TCP
      name: http
    selector:
        app: "template1-9e44"